version: '3'
services:
    web:
        image: m4rku5/webdock
        container_name: webdock
        env_file: .env
        volumes: 
            - ~:/var/host
            # dev
            - ./docker:/var/docker
            - ./pac:/var/pac
            - ./project:/var/project
        ports:
            - ${DOCKER_PORT}:80
