version: '3'
services:
    web:
        image: m4rku5/webdock
        container_name: webdock
        env_file: .env
        volumes: 
            - ~:/var/host
            - ~/.composer:/var/composer/
            # dev
            - ./project:/var/project
            - ./docker:/var/docker
            - ./libs:/var/libs
            - ./pac:/var/pac
        ports:
            - ${DOCKER_PORT}:80
