version: '3'
services:
    web:
        image: m4rku5/webdock
        container_name: project
        env_file: .env
        volumes: 
            - '~:/var/host'
            - .:/var/project
        ports:
            - ${DOCKER_PORT}:80
        restart: no
